/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.arrendamientos;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        SetImageLabel(sidebarImg, "src/main/java/images/sidebar-bg.jpg");
//        SetImageLabel(jLabel2, "src/main/java/com/images/user128x128.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        userTitle = new javax.swing.JLabel();
        userImg = new javax.swing.JLabel();
        sidebarImg = new javax.swing.JLabel();
        logoName = new javax.swing.JLabel();
        loginTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        userInput = new javax.swing.JTextField();
        passTitle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        passInput = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        userTitle.setForeground(new java.awt.Color(0, 0, 0));
        userTitle.setText("USUARIO");
        background.add(userTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        userImg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\diego\\Documents\\NetBeansProjects\\Arrendamiento\\src\\main\\java\\images\\user128x128.png")); // NOI18N
        background.add(userImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 280, -1));

        sidebarImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        background.add(sidebarImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 280, 572));

        logoName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        logoName.setForeground(new java.awt.Color(0, 0, 0));
        logoName.setIcon(new javax.swing.ImageIcon("C:\\Users\\diego\\Documents\\NetBeansProjects\\Arrendamiento\\src\\main\\java\\images\\favicon.png")); // NOI18N
        logoName.setText("LOGO");
        background.add(logoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 140, 30));

        loginTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginTitle.setForeground(new java.awt.Color(0, 0, 0));
        loginTitle.setText("INICIAR SESIÓN");
        background.add(loginTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 390, 20));

        userInput.setBackground(new java.awt.Color(255, 255, 255));
        userInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userInput.setForeground(new java.awt.Color(204, 204, 204));
        userInput.setText("Ingrese su nombre de usuario");
        userInput.setBorder(null);
        userInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userInputMousePressed(evt);
            }
        });
        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });
        background.add(userInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 390, 30));

        passTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passTitle.setForeground(new java.awt.Color(0, 0, 0));
        passTitle.setText("CONTRASEÑA");
        background.add(passTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 30));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 390, 20));

        passInput.setBackground(new java.awt.Color(255, 255, 255));
        passInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passInput.setForeground(new java.awt.Color(204, 204, 204));
        passInput.setText("****");
        passInput.setBorder(null);
        passInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passInputMousePressed(evt);
            }
        });
        passInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passInputActionPerformed(evt);
            }
        });
        background.add(passInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 390, 30));

        btnLogin.setBackground(new java.awt.Color(0, 204, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("ENTRAR");
        btnLogin.setBorder(null);
        background.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userInputMousePressed
        if (userInput.getText().equals("Ingrese su nombre de usuario")){
            userInput.setText("");
            userInput.setForeground(Color.BLACK);
        }
        if (String.valueOf(passInput.getPassword()).isEmpty()){
            passInput.setText("****");
            passInput.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_userInputMousePressed

    private void passInputMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passInputMousePressed
        if (String.valueOf(passInput.getPassword()).equals("****")){
            passInput.setText("");
            passInput.setForeground(Color.BLACK);
        }
        if (userInput.getText().isEmpty()){
            userInput.setText("Ingrese su nombre de usuario");
            userInput.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_passInputMousePressed

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInputActionPerformed

    private void passInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    private void SetImageLabel(JLabel labelName, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT)
        );
        labelName.setIcon(icon);
        this.repaint();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton btnLogin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel loginTitle;
    private javax.swing.JLabel logoName;
    private javax.swing.JPasswordField passInput;
    private javax.swing.JLabel passTitle;
    private javax.swing.JLabel sidebarImg;
    private javax.swing.JLabel userImg;
    private javax.swing.JTextField userInput;
    private javax.swing.JLabel userTitle;
    // End of variables declaration//GEN-END:variables
}
